apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-microproject-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/logs"